/**
 * Source for the bundled coworking MCP server script.
 *
 * The agent's MCP client spawns this script as a stdio subprocess (per the user-level
 * MCP config we install via `coworking-installer`). The subprocess speaks the MCP wire
 * protocol on stdin/stdout, and connects back to Maestro main via the Unix-domain
 * socket / named pipe whose path is in `MAESTRO_COWORKING_SOCKET`.
 *
 * We write the script as a self-contained CommonJS file to `<userData>/coworking-mcp-server.js`
 * on every app `ready`. That gives us:
 *   - a stable absolute path users can reference in their MCP config (survives upgrades)
 *   - no dependency on the Maestro app bundle being on disk at a known path
 *   - no bundler step in PR #1 (script is plain Node — only built-ins)
 *
 * The script implements just enough of the MCP stdio protocol to advertise our two
 * read-only tools (`list_terminals`, `read_terminal`). Anything richer (subscriptions,
 * resource templates, prompts) is a later PR.
 */

const COWORKING_SCRIPT_SOURCE = String.raw`#!/usr/bin/env node
"use strict";
/**
 * Maestro Coworking — MCP stdio server.
 * AUTOGENERATED by Maestro. Do not edit; this file is overwritten on every Maestro launch.
 *
 * Speaks MCP JSON-RPC on stdin/stdout. Translates 'tools/list' and 'tools/call' into
 * IPC requests against the parent Maestro app via a Unix socket / named pipe.
 *
 * Spec: https://modelcontextprotocol.io/specification (subset).
 */
const net = require('net');

const SOCKET_PATH = process.env.MAESTRO_COWORKING_SOCKET;
if (!SOCKET_PATH) {
  process.stderr.write('[maestro-coworking] MAESTRO_COWORKING_SOCKET env var is required\n');
  process.exit(1);
}

// SESSION_ID identifies which Maestro session (left-bar agent) owns this MCP
// subprocess. Set by the main process at agent-CLI spawn time and inherited
// down through the agent CLI when it spawns its MCP subprocesses. Without it
// we cannot prove which session is calling, and would risk leaking another
// session's terminals — fail closed.
const SESSION_ID = process.env.MAESTRO_COWORKING_SESSION_ID;
if (!SESSION_ID) {
  process.stderr.write(
    '[maestro-coworking] MAESTRO_COWORKING_SESSION_ID env var is required. ' +
    'If you are running this MCP server outside Maestro, this is expected. ' +
    'Inside Maestro, restart the agent so the new env reaches the MCP subprocess.\n'
  );
  process.exit(1);
}

const SERVER_INFO = { name: 'maestro-coworking', version: '1.0.0' };
// Listed newest-first. The MCP spec says: if the client requests a version we
// support, echo it back; otherwise pick one we do support. We pick the newest
// supported version as the fallback (also our preferred version when the client
// sends nothing). https://modelcontextprotocol.io/specification/.../basic/lifecycle
const SUPPORTED_PROTOCOL_VERSIONS = [
  '2025-11-25',
  '2025-06-18',
  '2025-03-26',
  '2024-11-05',
  '2024-10-07',
];
const TOOLS = [
  {
    name: 'list_terminals',
    description:
      'List terminal tabs in your own Maestro session (the agent that spawned this MCP server). ' +
      'Returns an array of { id, cwd, title } where id is a stable readable handle like "term:3". ' +
      'You will never see terminals belonging to other Maestro sessions, regardless of which tab the user has focused.',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'read_terminal',
    description:
      'Read the scrollback contents of a terminal tab by id, scoped to your own Maestro session. ' +
      'Optionally tail-truncate to the last N lines.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Terminal id, e.g. "term:3" (from list_terminals).' },
        lines: { type: 'integer', minimum: 1, description: 'If set, return only the last N lines.' },
      },
      required: ['id'],
      additionalProperties: false,
    },
  },
];

// ---------- Bridge client (lazy, single shared connection) ----------
let bridgeConn = null;
let bridgeBuffer = '';
let connectPromise = null;
let helloPromise = null;
const pending = new Map();
let nextRpcId = 1;
// Cap each in-flight RPC so a wedged-but-not-disconnected bridge can't stall
// tools/call indefinitely. 10s comfortably accommodates a renderer round-trip
// (the main-process side caps the buffer-fetch at 5s) plus jitter.
const BRIDGE_RPC_TIMEOUT_MS = 10000;

function rejectAllPending(err) {
  for (const p of pending.values()) p.reject(err);
  pending.clear();
}

function connectBridge() {
  if (bridgeConn) return Promise.resolve(bridgeConn);
  // Concurrent callers must share a single in-flight connection so the module-
  // level bridgeBuffer doesn't get spliced across multiple sockets.
  if (connectPromise) return connectPromise;

  connectPromise = new Promise((resolve, reject) => {
    const c = net.createConnection({ path: SOCKET_PATH }, () => {
      c.setEncoding('utf8');
      // Reset shared buffer for this fresh connection.
      bridgeBuffer = '';
      c.on('data', (chunk) => {
        bridgeBuffer += chunk;
        let nl;
        while ((nl = bridgeBuffer.indexOf('\n')) !== -1) {
          const line = bridgeBuffer.slice(0, nl).trim();
          bridgeBuffer = bridgeBuffer.slice(nl + 1);
          if (!line) continue;
          let msg;
          try {
            msg = JSON.parse(line);
          } catch {
            continue;
          }
          const p = pending.get(msg.id);
          if (!p) continue;
          pending.delete(msg.id);
          if (msg.error) p.reject(new Error(msg.error.message || 'bridge error'));
          else p.resolve(msg.result);
        }
      });
      c.on('error', (err) => {
        rejectAllPending(err);
        bridgeConn = null;
        helloPromise = null;
      });
      // Reject pending RPCs on a clean close too — otherwise their callers
      // would hang forever waiting for a reply that will never come.
      c.on('close', () => {
        rejectAllPending(new Error('coworking bridge: connection closed'));
        bridgeConn = null;
        helloPromise = null;
      });
      bridgeConn = c;
      resolve(c);
    });
    c.once('error', reject);
  }).finally(() => {
    connectPromise = null;
  });
  return connectPromise;
}

// Send a single RPC against an already-open bridge connection. No handshake
// gating here — the gate lives in bridgeCall() so this primitive can also be
// used to perform the handshake itself.
function rpc(conn, method, params) {
  const id = nextRpcId++;
  let timeoutHandle = null;
  const promise = new Promise((resolve, reject) => {
    timeoutHandle = setTimeout(() => {
      // Drop the pending entry first so the response (if it ever arrives) is a no-op.
      pending.delete(id);
      reject(new Error('coworking bridge: rpc timed out'));
    }, BRIDGE_RPC_TIMEOUT_MS);
    pending.set(id, {
      resolve: (value) => {
        if (timeoutHandle) clearTimeout(timeoutHandle);
        resolve(value);
      },
      reject: (err) => {
        if (timeoutHandle) clearTimeout(timeoutHandle);
        reject(err);
      },
    });
  });
  try {
    conn.write(JSON.stringify({ id, method, params }) + '\n');
  } catch (err) {
    if (timeoutHandle) clearTimeout(timeoutHandle);
    pending.delete(id);
    throw err;
  }
  return promise;
}

// Perform the session-binding handshake exactly once per connection. Cached on
// helloPromise so concurrent first callers share one in-flight handshake; the
// connect-close handlers reset it so a reconnect re-handshakes.
function bridgeHello(conn) {
  if (helloPromise) return helloPromise;
  helloPromise = rpc(conn, 'hello', { sessionId: SESSION_ID }).catch((err) => {
    helloPromise = null;
    throw err;
  });
  return helloPromise;
}

async function bridgeCall(method, params) {
  // Capture the resolved socket locally so that if bridgeConn is nulled out
  // between the await and the write (e.g. by a synchronous error handler), we
  // either succeed or surface the failure immediately instead of leaking the
  // pending entry.
  const conn = bridgeConn || (await connectBridge());
  if (!conn || conn.destroyed) {
    throw new Error('coworking bridge: not connected');
  }
  await bridgeHello(conn);
  return rpc(conn, method, params);
}

// ---------- MCP stdio framing ----------
let stdinBuffer = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  stdinBuffer += chunk;
  let nl;
  while ((nl = stdinBuffer.indexOf('\n')) !== -1) {
    const line = stdinBuffer.slice(0, nl).trim();
    stdinBuffer = stdinBuffer.slice(nl + 1);
    if (!line) continue;
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      continue;
    }
    handleMessage(msg).catch((err) => {
      process.stderr.write('[maestro-coworking] handler error: ' + String(err) + '\n');
    });
  }
});

function send(msg) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

function rpcResult(id, result) {
  return { jsonrpc: '2.0', id, result };
}
function rpcError(id, code, message) {
  return { jsonrpc: '2.0', id, error: { code, message } };
}

async function handleMessage(msg) {
  // Notifications: no id, no response.
  if (msg.id === undefined || msg.id === null) {
    // 'notifications/initialized' and others — ignore.
    return;
  }
  const { id, method, params } = msg;
  try {
    if (method === 'initialize') {
      const requested = params && params.protocolVersion;
      const protocolVersion =
        typeof requested === 'string' && SUPPORTED_PROTOCOL_VERSIONS.indexOf(requested) !== -1
          ? requested
          : SUPPORTED_PROTOCOL_VERSIONS[0];
      send(
        rpcResult(id, {
          protocolVersion,
          serverInfo: SERVER_INFO,
          capabilities: { tools: {} },
        })
      );
      return;
    }
    if (method === 'ping') {
      send(rpcResult(id, {}));
      return;
    }
    if (method === 'tools/list') {
      send(rpcResult(id, { tools: TOOLS }));
      return;
    }
    if (method === 'tools/call') {
      const name = params && params.name;
      const args = (params && params.arguments) || {};
      if (name === 'list_terminals') {
        const result = await bridgeCall('listTerminals', {});
        const text = JSON.stringify(result, null, 2);
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (name === 'read_terminal') {
        const result = await bridgeCall('readTerminal', args);
        const header =
          'terminal=' +
          (result && result.id) +
          ' totalLines=' +
          (result && result.totalLines) +
          (result && result.truncated ? ' (tail-truncated)' : '');
        const text = header + '\n----- BEGIN BUFFER -----\n' + (result && result.content) + '\n----- END BUFFER -----';
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      send(rpcError(id, -32601, 'Unknown tool: ' + String(name)));
      return;
    }
    send(rpcError(id, -32601, 'Unknown method: ' + String(method)));
  } catch (err) {
    send(rpcError(id, -32000, err && err.message ? err.message : String(err)));
  }
}

// Keep stdin alive so the agent's MCP client controls our lifecycle.
process.stdin.on('end', () => process.exit(0));
process.on('SIGINT', () => process.exit(0));
process.on('SIGTERM', () => process.exit(0));
`;

/** Returns the contents of the bundled MCP server script. */
export function getCoworkingServerScript(): string {
	return COWORKING_SCRIPT_SOURCE;
}
