/**
 * Source for the bundled coworking MCP server script.
 *
 * The agent's MCP client spawns this script as a stdio subprocess (per the user-level
 * MCP config we install via `coworking-installer`). The subprocess speaks the MCP wire
 * protocol on stdin/stdout, and connects back to Maestro main via the Unix-domain
 * socket / named pipe whose path is in `MAESTRO_COWORKING_SOCKET`.
 *
 * We write the script as a self-contained CommonJS file to `<userData>/coworking-mcp-server.js`
 * on every app `ready`. That gives us:
 *   - a stable absolute path users can reference in their MCP config (survives upgrades)
 *   - no dependency on the Maestro app bundle being on disk at a known path
 *   - no bundler step in PR #1 (script is plain Node — only built-ins)
 *
 * The script implements just enough of the MCP stdio protocol to advertise our two
 * read-only tools (`list_terminals`, `read_terminal`). Anything richer (subscriptions,
 * resource templates, prompts) is a later PR.
 */

const COWORKING_SCRIPT_SOURCE = String.raw`#!/usr/bin/env node
"use strict";
/**
 * Maestro Coworking — MCP stdio server.
 * AUTOGENERATED by Maestro. Do not edit; this file is overwritten on every Maestro launch.
 *
 * Speaks MCP JSON-RPC on stdin/stdout. Translates 'tools/list' and 'tools/call' into
 * IPC requests against the parent Maestro app via a Unix socket / named pipe.
 *
 * Spec: https://modelcontextprotocol.io/specification (subset).
 */
const net = require('net');

const SOCKET_PATH = process.env.MAESTRO_COWORKING_SOCKET;
if (!SOCKET_PATH) {
  process.stderr.write('[maestro-coworking] MAESTRO_COWORKING_SOCKET env var is required\n');
  process.exit(1);
}

const SERVER_INFO = { name: 'maestro-coworking', version: '1.0.0' };
const TOOLS = [
  {
    name: 'list_terminals',
    description:
      "List terminal tabs visible to the agent in the user's currently active AI tab session. " +
      'Returns an array of { id, cwd, title } where id is a stable readable handle like "term:3".',
    inputSchema: { type: 'object', properties: {}, additionalProperties: false },
  },
  {
    name: 'read_terminal',
    description:
      'Read the scrollback contents of a terminal tab by id. Optionally tail-truncate to the last N lines.',
    inputSchema: {
      type: 'object',
      properties: {
        id: { type: 'string', description: 'Terminal id, e.g. "term:3" (from list_terminals).' },
        lines: { type: 'integer', minimum: 1, description: 'If set, return only the last N lines.' },
      },
      required: ['id'],
      additionalProperties: false,
    },
  },
];

// ---------- Bridge client (lazy, with one-shot reconnect) ----------
let bridgeConn = null;
let bridgeBuffer = '';
const pending = new Map();
let nextRpcId = 1;

function connectBridge() {
  return new Promise((resolve, reject) => {
    const c = net.createConnection({ path: SOCKET_PATH }, () => {
      c.setEncoding('utf8');
      c.on('data', (chunk) => {
        bridgeBuffer += chunk;
        let nl;
        while ((nl = bridgeBuffer.indexOf('\n')) !== -1) {
          const line = bridgeBuffer.slice(0, nl).trim();
          bridgeBuffer = bridgeBuffer.slice(nl + 1);
          if (!line) continue;
          let msg;
          try {
            msg = JSON.parse(line);
          } catch {
            continue;
          }
          const p = pending.get(msg.id);
          if (!p) continue;
          pending.delete(msg.id);
          if (msg.error) p.reject(new Error(msg.error.message || 'bridge error'));
          else p.resolve(msg.result);
        }
      });
      c.on('error', (err) => {
        for (const p of pending.values()) p.reject(err);
        pending.clear();
        bridgeConn = null;
      });
      c.on('close', () => {
        bridgeConn = null;
      });
      bridgeConn = c;
      resolve(c);
    });
    c.once('error', reject);
  });
}

async function bridgeCall(method, params) {
  if (!bridgeConn) await connectBridge();
  const id = nextRpcId++;
  const promise = new Promise((resolve, reject) => pending.set(id, { resolve, reject }));
  bridgeConn.write(JSON.stringify({ id, method, params }) + '\n');
  return promise;
}

// ---------- MCP stdio framing ----------
let stdinBuffer = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  stdinBuffer += chunk;
  let nl;
  while ((nl = stdinBuffer.indexOf('\n')) !== -1) {
    const line = stdinBuffer.slice(0, nl).trim();
    stdinBuffer = stdinBuffer.slice(nl + 1);
    if (!line) continue;
    let msg;
    try {
      msg = JSON.parse(line);
    } catch {
      continue;
    }
    handleMessage(msg).catch((err) => {
      process.stderr.write('[maestro-coworking] handler error: ' + String(err) + '\n');
    });
  }
});

function send(msg) {
  process.stdout.write(JSON.stringify(msg) + '\n');
}

function rpcResult(id, result) {
  return { jsonrpc: '2.0', id, result };
}
function rpcError(id, code, message) {
  return { jsonrpc: '2.0', id, error: { code, message } };
}

async function handleMessage(msg) {
  // Notifications: no id, no response.
  if (msg.id === undefined || msg.id === null) {
    // 'notifications/initialized' and others — ignore.
    return;
  }
  const { id, method, params } = msg;
  try {
    if (method === 'initialize') {
      send(
        rpcResult(id, {
          protocolVersion: '2025-06-18',
          serverInfo: SERVER_INFO,
          capabilities: { tools: {} },
        })
      );
      return;
    }
    if (method === 'ping') {
      send(rpcResult(id, {}));
      return;
    }
    if (method === 'tools/list') {
      send(rpcResult(id, { tools: TOOLS }));
      return;
    }
    if (method === 'tools/call') {
      const name = params && params.name;
      const args = (params && params.arguments) || {};
      if (name === 'list_terminals') {
        const result = await bridgeCall('listTerminals', {});
        const text = JSON.stringify(result, null, 2);
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      if (name === 'read_terminal') {
        const result = await bridgeCall('readTerminal', args);
        const header =
          'terminal=' +
          (result && result.id) +
          ' totalLines=' +
          (result && result.totalLines) +
          (result && result.truncated ? ' (tail-truncated)' : '');
        const text = header + '\n----- BEGIN BUFFER -----\n' + (result && result.content) + '\n----- END BUFFER -----';
        send(rpcResult(id, { content: [{ type: 'text', text }] }));
        return;
      }
      send(rpcError(id, -32601, 'Unknown tool: ' + String(name)));
      return;
    }
    send(rpcError(id, -32601, 'Unknown method: ' + String(method)));
  } catch (err) {
    send(rpcError(id, -32000, err && err.message ? err.message : String(err)));
  }
}

// Keep stdin alive so the agent's MCP client controls our lifecycle.
process.stdin.on('end', () => process.exit(0));
process.on('SIGINT', () => process.exit(0));
process.on('SIGTERM', () => process.exit(0));
`;

/** Returns the contents of the bundled MCP server script. */
export function getCoworkingServerScript(): string {
	return COWORKING_SCRIPT_SOURCE;
}
